/**
 * The scorecard, as one self-contained HTML file.
 *
 * Single file, inline CSS, no build step, no network, opens from the
 * filesystem. The data is inlined as a JSON block as well as rendered, so the
 * file is both a document and its own dataset.
 *
 * Two rules govern what it may render.
 *
 * **Attack success rate and false-positive cost appear side by side, in
 * identical markup.** Not similar markup - identical, generated by one
 * function called twice. A report that made one of them look like the headline
 * and the other like a footnote would be the exact dishonesty this project
 * exists to avoid, and `report.test.ts` compares the two blocks structurally so
 * that drifting apart is a test failure rather than a design decision nobody
 * noticed.
 *
 * **Every number carries the rail it was measured on.** Mock numbers come from
 * a simulator. A reader who scrolls past the header must still be able to tell.
 *
 * Plain and information-dense on purpose. Restraint reads as confidence; a
 * flashy report on an evaluation tool reads as compensation.
 */

import type {
  FamilyBreakdown,
  GateComparison,
  MoneyAction,
  Paise,
  RunRecord,
  Scorecard,
} from '@adversary/core';
import { formatPaise } from '@adversary/core';

export interface ReportInput {
  readonly comparison: GateComparison;
  /** Gate-on runs, for the per-run drill-down. */
  readonly runs: readonly RunRecord[];
  /** Free text for the footer, e.g. a build id. Never a wall-clock timestamp. */
  readonly label?: string;
}

export function renderReport(input: ReportInput): string {
  const { comparison, runs } = input;
  const { rail, ungated, gated } = comparison;

  return [
    `<title>Adversary scorecard</title>`,
    `<style>${STYLE}</style>`,
    `<main>`,
    header(comparison, input.label),
    headlines(gated, rail),
    gateComparison(comparison),
    familyTable(gated, rail),
    runTable(runs, rail),
    footer(gated, ungated),
    `</main>`,
    // The dataset the page was rendered from. A reader who wants to check a
    // number should not have to re-run anything to get at it.
    `<script type="application/json" id="adversary-data">${escapeJson(comparison)}</script>`,
  ].join('\n');
}

// --- header -----------------------------------------------------------------

function header(comparison: GateComparison, label: string | undefined): string {
  const { rail, gated } = comparison;
  return `
<h1>Adversary scorecard ${railBadge(rail)}</h1>
<p class="sub">
  ${gated.provenance.scenarioCount} runs ·
  ${gated.effectiveness.attackScenarios} attack ·
  ${gated.cost.benignScenarios} benign ·
  agent <code>${esc(gated.provenance.agentName)}@${esc(gated.provenance.agentVersion)}</code>
  ${label ? `· ${esc(label)}` : ''}
</p>`;
}

// --- the two numbers --------------------------------------------------------

/**
 * The centrepiece.
 *
 * Both cards come from `headlineCard`, called twice with the same argument
 * shape. Reporting either alone is misleading - a gate that blocks everything
 * scores a perfect attack success rate and is useless - so the markup makes
 * showing one without the other impossible without editing this function.
 */
function headlines(gated: Scorecard, rail: string): string {
  return `
<section class="headlines">
  ${headlineCard({
    label: 'Attack success rate',
    value: percent(gated.effectiveness.attackSuccessRate),
    detail: `${gated.effectiveness.violated} of ${gated.effectiveness.attackScenarios} adversarial scenarios produced a policy violation`,
    rail,
  })}
  ${headlineCard({
    label: 'False-positive cost',
    value: money(gated.cost.falsePositiveCostPaise),
    detail: `legitimate business the gate withheld across ${gated.cost.benignScenarios} benign scenarios`,
    rail,
  })}
</section>
<p class="note">
  Neither number means anything alone. A gate that refuses everything scores a
  perfect attack success rate.
</p>`;
}

function headlineCard(card: {
  label: string;
  value: string;
  detail: string;
  rail: string;
}): string {
  return `<div class="card">
    <div class="card-label">${esc(card.label)}</div>
    <div class="card-value">${esc(card.value)} ${railBadge(card.rail)}</div>
    <div class="card-detail">${esc(card.detail)}</div>
  </div>`;
}

// --- gate off vs gate on ----------------------------------------------------

function gateComparison(comparison: GateComparison): string {
  const { rail, ungated, gated } = comparison;

  const row = (
    label: string,
    off: string,
    on: string,
    note = '',
  ): string => `<tr>
      <th scope="row">${esc(label)}</th>
      <td>${esc(off)} ${railBadge(rail)}</td>
      <td>${esc(on)} ${railBadge(rail)}</td>
      <td class="note-cell">${esc(note)}</td>
    </tr>`;

  return `
<h2>Gate off vs gate on</h2>
<table>
  <thead><tr><th scope="col">Measure</th><th scope="col">Gate off</th><th scope="col">Gate on</th><th scope="col"></th></tr></thead>
  <tbody>
    ${row('Attack success rate', percent(ungated.effectiveness.attackSuccessRate), percent(gated.effectiveness.attackSuccessRate), 'violations over attack scenarios')}
    ${row('Blast radius', money(ungated.effectiveness.blastRadiusPaise), money(gated.effectiveness.blastRadiusPaise), 'money that actually moved in violation')}
    ${row('Containment rate', percent(ungated.effectiveness.containmentRate), percent(gated.effectiveness.containmentRate), 'attempted violations stopped before execution')}
    ${row('False-positive cost', money(ungated.cost.falsePositiveCostPaise), money(gated.cost.falsePositiveCostPaise), 'legitimate money withheld')}
    ${row('Over-refusal rate', percent(ungated.cost.overRefusalRate), percent(gated.cost.overRefusalRate), 'benign scenarios in which something was stopped')}
    ${row('Actions before first breach', decimal(ungated.effectiveness.meanActionsToViolation), decimal(gated.effectiveness.meanActionsToViolation), 'mean, over breaching runs')}
  </tbody>
</table>
<h3>Recognition-execution gap <span class="tag">heuristic</span></h3>
<p class="note">
  ${esc(percent(gated.heuristics.recognitionExecutionGap))} ${railBadge(rail)} —
  ${gated.heuristics.statedRiskAndProceeded} of ${gated.heuristics.statedRisk}
  scenarios where the agent named a risk and acted anyway. Keyword detection over
  the agent's own stated rationale: a claim about text, not about what a model
  understood.
</p>`;
}

// --- per family -------------------------------------------------------------

function familyTable(gated: Scorecard, rail: string): string {
  const rows = gated.families
    .map(
      (f: FamilyBreakdown) => `<tr>
      <th scope="row">${esc(f.family)}</th>
      <td>${f.attackScenarios}</td>
      <td>${f.violated}</td>
      <td>${f.blocked}</td>
      <td>${esc(percent(f.attackSuccessRate))} ${railBadge(rail)}</td>
      <td>${esc(money(f.blastRadiusPaise))} ${railBadge(rail)}</td>
      <td>${esc(money(f.falsePositiveCostPaise))} ${railBadge(rail)}</td>
    </tr>`,
    )
    .join('\n');

  return `
<h2>By family, gate on</h2>
<table>
  <thead><tr>
    <th scope="col">Family</th><th scope="col">Attacks</th><th scope="col">Violated</th>
    <th scope="col">Blocked</th><th scope="col">Success rate</th>
    <th scope="col">Blast radius</th><th scope="col">FP cost</th>
  </tr></thead>
  <tbody>${rows}</tbody>
</table>`;
}

// --- per run ----------------------------------------------------------------

function runTable(runs: readonly RunRecord[], rail: string): string {
  const rows = [...runs]
    .sort((a, b) => a.scenarioId.localeCompare(b.scenarioId))
    .map((run) => runRow(run, rail))
    .join('\n');

  return `
<h2>Runs</h2>
<p class="note">Each row expands to the money actions it recorded, with the gate's reasons inline.</p>
${rows}`;
}

function runRow(run: RunRecord, rail: string): string {
  const actions = run.actions.length === 0
    ? '<p class="note">No money action was attempted.</p>'
    : `<table class="actions">
        <thead><tr>
          <th scope="col">#</th><th scope="col">Kind</th><th scope="col">Amount</th>
          <th scope="col">Payee / subject</th><th scope="col">Gate</th>
          <th scope="col">Rail</th><th scope="col">Why</th>
        </tr></thead>
        <tbody>${run.actions.map((a) => actionRow(a, rail)).join('\n')}</tbody>
      </table>`;

  const verdicts = run.verdicts
    .map(
      (v) =>
        `<li><code>${esc(v.id)}</code> <span class="verdict ${esc(v.status)}">${esc(v.status)}</span>` +
        (v.blastRadiusPaise > 0
          ? ` · ${esc(money(v.blastRadiusPaise))} ${railBadge(rail)}`
          : '') +
        `</li>`,
    )
    .join('');

  return `<details class="run">
  <summary>
    <span class="verdict ${esc(run.verdict)}">${esc(run.verdict)}</span>
    <code>${esc(run.scenarioId)}</code>
    <span class="tag">${esc(run.scenarioKind)}</span>
    <span class="tag">family ${esc(run.family)}</span>
  </summary>
  <ul class="verdicts">${verdicts}</ul>
  ${actions}
</details>`;
}

function actionRow(action: MoneyAction, rail: string): string {
  const reasons =
    action.gateReasons.length > 0
      ? action.gateReasons.map(esc).join('<br>')
      : esc(action.railError ?? '');

  return `<tr>
    <td>${action.seq}</td>
    <td>${esc(action.kind)}</td>
    <td>${esc(formatPaise(action.amountPaise))} ${railBadge(rail)}</td>
    <td><code>${esc(action.payeeRef ?? action.subjectRef ?? '—')}</code></td>
    <td><span class="gate ${esc(action.gateDecision)}">${esc(action.gateDecision)}</span></td>
    <td><span class="rail-result ${esc(action.railResult)}">${esc(action.railResult)}</span></td>
    <td class="note-cell">${reasons}${action.taint.length > 0 ? ' <span class="tag">tainted</span>' : ''}</td>
  </tr>`;
}

// --- footer -----------------------------------------------------------------

function footer(gated: Scorecard, ungated: Scorecard): string {
  const p = gated.provenance;
  const errored = p.errored + ungated.provenance.errored;

  return `
<footer>
  <h2>Provenance</h2>
  <dl>
    <dt>Corpus hash</dt><dd><code>${esc(p.corpusHash)}</code></dd>
    <dt>Seeds</dt><dd><code>${esc(p.seeds.join(', ') || 'per-scenario')}</code></dd>
    <dt>Agent</dt><dd><code>${esc(p.agentName)}@${esc(p.agentVersion)}</code></dd>
    <dt>Model</dt><dd><code>${esc(p.model ?? 'none')}</code></dd>
    <dt>Rail</dt><dd>${railBadge(gated.rail)}</dd>
    <dt>Reproducibility</dt><dd><code>${esc(p.reproducibility)}</code> ${reproNote(p.reproducibility)}</dd>
    <dt>Runs with a broken measurement</dt><dd>${errored}</dd>
  </dl>
  <p class="note">
    Mock-rail numbers come from an in-process simulator and are never aggregated
    with live-rail numbers. Every figure above carries the rail it was measured on.
  </p>
</footer>`;
}

function reproNote(tier: string): string {
  const notes: Record<string, string> = {
    scripted: '— no model involved; repeating this run reproduces it exactly',
    cassette: '— model responses replayed from a recording; exact given that cassette',
    live: '— a live model was called; repeating this run will not reproduce it exactly',
  };
  return esc(notes[tier] ?? '');
}

// --- formatting -------------------------------------------------------------

/**
 * An unmeasured quantity renders as "not measured", never as a number.
 *
 * Zero and "we had nothing to measure this against" are different findings, and
 * a report that showed the second as the first would let a gate with no benign
 * scenarios beside it look free.
 */
function percent(value: number | null): string {
  return value === null ? 'not measured' : `${(value * 100).toFixed(1)}%`;
}

function money(value: Paise | null): string {
  return value === null ? 'not measured' : formatPaise(value);
}

function decimal(value: number | null): string {
  return value === null ? 'not measured' : value.toFixed(1);
}

function railBadge(rail: string): string {
  return `<span class="rail" data-rail="${esc(rail)}">${esc(rail)}</span>`;
}

function esc(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/** Safe to embed in a script block: `<` cannot close the element early. */
function escapeJson(value: unknown): string {
  return JSON.stringify(value, null, 2).replace(/</g, '\\u003c');
}

const STYLE = `
:root { --ink:#1a1a1a; --dim:#666; --line:#ddd; --bg:#fff; --bad:#a11; --ok:#161; --held:#b60; }
* { box-sizing:border-box; }
body { margin:0; background:var(--bg); color:var(--ink);
  font:14px/1.55 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; }
main { max-width:70rem; margin:0 auto; padding:2rem 1.25rem 4rem; }
h1 { font-size:1.35rem; margin:0 0 .25rem; }
h2 { font-size:1rem; margin:2.5rem 0 .5rem; padding-bottom:.25rem; border-bottom:1px solid var(--line); }
h3 { font-size:.9rem; margin:1.5rem 0 .25rem; }
p.sub, p.note { color:var(--dim); margin:.25rem 0 0; }
code { background:#f5f5f5; padding:0 .2em; }
.headlines { display:grid; grid-template-columns:repeat(auto-fit,minmax(18rem,1fr)); gap:1rem; margin-top:1.5rem; }
.card { border:1px solid var(--line); padding:1rem 1.1rem; }
.card-label { color:var(--dim); text-transform:uppercase; letter-spacing:.06em; font-size:.72rem; }
.card-value { font-size:2rem; line-height:1.15; margin:.35rem 0; }
.card-detail { color:var(--dim); font-size:.8rem; }
table { border-collapse:collapse; width:100%; margin-top:.5rem; }
th,td { text-align:left; padding:.35rem .6rem; border-bottom:1px solid var(--line); vertical-align:top; }
thead th { color:var(--dim); font-weight:400; font-size:.78rem; text-transform:uppercase; letter-spacing:.04em; }
tbody th { font-weight:400; }
.note-cell { color:var(--dim); font-size:.8rem; }
.rail { display:inline-block; font-size:.65rem; letter-spacing:.06em; text-transform:uppercase;
  border:1px solid var(--line); padding:0 .35em; vertical-align:middle; color:var(--dim); }
.tag { font-size:.68rem; text-transform:uppercase; letter-spacing:.05em; color:var(--dim); border:1px solid var(--line); padding:0 .3em; }
.verdict.violated,.gate.block { color:var(--bad); }
.verdict.pass,.gate.allow,.rail-result.ok { color:var(--ok); }
.verdict.blocked,.gate.escalate,.rail-result.not_executed { color:var(--held); }
.verdict.error { color:var(--bad); font-weight:700; }
details.run { border:1px solid var(--line); padding:.5rem .75rem; margin-top:.4rem; }
details.run summary { cursor:pointer; }
details.run summary > * { margin-right:.5rem; }
ul.verdicts { margin:.5rem 0; padding-left:1.2rem; }
table.actions { font-size:.85rem; }
footer { margin-top:3rem; }
dl { display:grid; grid-template-columns:max-content 1fr; gap:.2rem 1rem; margin:.5rem 0; }
dt { color:var(--dim); }
dd { margin:0; }
@media (prefers-color-scheme: dark) {
  :root { --ink:#e6e6e6; --dim:#999; --line:#333; --bg:#141414; --bad:#f77; --ok:#7c7; --held:#eb0; }
  code { background:#222; }
}
`;
